In [14]:
import numpy as np

---

## **1. Algoritmo de multiplcacion de matrices**

In [15]:
def matrix_mult(A,B):
    '''
    A es una matriz nxm B es una matrix mxp
    
    Metodo retorna la multiplicacion matricial AB
    
    '''
    n = A.shape[0]
    m_a = A.shape[1]
    
    #Si B es un vector columna:
    if B.ndim==1:
        C = np.zeros(n)
        for i in range(m_a):
            #Combinacion lineal de los vectores columna de A, y los escalares como entradas de B 
            C +=B[i]*A[:,i]
        return C
    
    m_b = B.shape[0]
    p = B.shape[1]
    if m_a!=m_b:
        print("Dimensiones no coinciden")
        return None
    
    C = np.zeros((n,p))
    
    for i in range(n):
        for j in range(p):
            C[i,j] = np.dot(A[i,:],B[:,j])
    return C

## **a)**

In [16]:
A = np.array([
    [5,-4,-2],
    [5,-5,4],
    [2,5,-4],
    [-5,4,3],
    [3,-4,-3]
]
)

B = np.array([5,-2,-3])

matrix_mult(A,B)

array([ 39.,  23.,  12., -42.,  32.])

## **b)**

In [17]:
A = np.array([
    [0,-1,-1,3],
    [5,-5,-2,2],
    [1,0,4,5]
])

B = np.array([
    [0,-3],
    [-2,-1],
    [3,-3]]
)

matrix_mult(A,B)

Dimensiones no coinciden


## **c)**

In [18]:
A = np.array([
    [2,-5,5,1],
    [5,2,-7,-6],
    [-6,-1,7,-4],
    [5,4,1,-5]
])

B = np.array([
    [0,4,-7,1,-6],
    [-1,-6,-5,1,1],
    [2,-1,-6,5,-5],
    [3,-6,6,3,5]
])

In [19]:
matrix_mult(A,B)

array([[ 18.,  27., -13.,  25., -37.],
       [-34.,  51., -39., -46., -23.],
       [  3.,  -1., -19.,  16., -20.],
       [-17.,  25., -91.,  -1., -56.]])

## **Multiplicacion de matrices no es conmutativa**

In [20]:
A = np.array([[1,2],
            [-1,0]])

In [21]:
B = np.array([[0,np.pi],
            [-1,0]])

In [22]:
matrix_mult(A,B)

array([[-2.        ,  3.14159265],
       [ 0.        , -3.14159265]])

In [23]:
matrix_mult(B,A)

array([[-3.14159265,  0.        ],
       [-1.        , -2.        ]])

----

## **2. Reduccion Gaussiana**

In [24]:
def triangular(M):
    '''Retorna una matriz triangular a partir de la matriz como parametro'''
    A = M.copy()
    
    for i in range(0, M.shape[0]):
        pivot = A[i,i]
        #print(pivot)
        A[i,:]= A[i,:]/A[i,i]
        for j in range(i+1,M.shape[0]):
            k = A[j,i] 
            A[j,:]-= k*A[i,:]
            
    return A

In [25]:
def back_substitution(M, b):
    '''
    Args:
        A (np.array): Matriz de coeficientes triangular superior
        b (np.arra): vector de constantes
        
    '''
    A= M.copy()
    
    n = np.shape(A)[0]

    x = np.zeros(n)

    for i in range(n-1,-1,-1):
        sum = b[i]
        for j in range(n-1,i,-1):
            sum -= A[i,j]*x[j]
        x[i] = sum/A[i,i]

    return x

## **a)**

In [26]:
A = np.array([
    [3,1,-1],
    [1,-2,1],
    [4,-1,1]
])

b = np.array([2,0,3])

n = np.shape(A)[0]
M = np.zeros(shape=(n,n+1))

M[:,0:n] = A
M[:,n] = b

In [27]:
M

array([[ 3.,  1., -1.,  2.],
       [ 1., -2.,  1.,  0.],
       [ 4., -1.,  1.,  3.]])

In [28]:
C = triangular(M)
C

array([[ 1.        ,  0.33333333, -0.33333333,  0.66666667],
       [-0.        ,  1.        , -0.57142857,  0.28571429],
       [ 0.        ,  0.        ,  1.        ,  1.        ]])

In [29]:
A = C[:,:3].copy()
b = C[:,3:].copy()

In [30]:
#Solucion
mysol = back_substitution(A,b)
mysol

array([0.71428571, 0.85714286, 1.        ])

## **b)**

In [31]:
A = np.array([
    [1.0,1.0,1.0],
    [0.0,-8.0,10.0],
    [4.0,-8.0,0.0]
])

b = np.array([0,0,6])

n = np.shape(A)[0]
M = np.zeros(shape=(n,n+1))

M[:,0:n] = A
M[:,n] = b

In [32]:
C = triangular(M)
C

array([[ 1.        ,  1.        ,  1.        ,  0.        ],
       [-0.        ,  1.        , -1.25      , -0.        ],
       [-0.        , -0.        ,  1.        , -0.31578947]])

In [33]:
A = C[:,:3].copy()
b = C[:,3:].copy()

In [34]:
#Solucion
mysol = back_substitution(A,b)
mysol

array([ 0.71052632, -0.39473684, -0.31578947])

---

## **3. Valores y vectores propios**

### **Cuando $\kappa = m_1=m_2=m_3=1$**

In [35]:
A = np.array([
    [-2.0,1.0,0.0],
    [1.0,-2.0,1.0],
    [0.0,1.0,-2.0]
])

### **Potencia Maxima**

In [36]:
#Algoritmo de la potencia 
zk = np.array([1.0,1.0,1.0])
i = 0
while i<20:
    #normalizar
    zk = (1/np.linalg.norm(zk))*zk
    #kesimo vector 
    zk = A@zk
    i+=1

In [37]:
valor_propio = ((zk.T@A)@zk)/np.linalg.norm(zk)**2
vector_propio = zk

In [38]:
print(f"Max valor propio de A i.e,. potencia maxima: {valor_propio}")
print(f"Vector propio asociado: {vector_propio}")

Max valor propio de A i.e,. potencia maxima: -3.414213562373095
Vector propio asociado: [ 1.70710678 -2.41421356  1.70710678]


**Verificacion**

In [39]:
A@vector_propio

array([-5.82842712,  8.24264069, -5.82842712])

In [40]:
valor_propio*vector_propio

array([-5.82842712,  8.24264069, -5.82842712])

### **Potencia Minima**

In [41]:
B = np.linalg.inv(A)

In [42]:
#Algoritmo de la potencia 
zk = np.array([1.0,1.0,1.0])
i = 0
while i<20:
    #normalizar
    zk = (1/np.linalg.norm(zk))*zk
    #kesimo vector 
    zk = B@zk
    i+=1

In [43]:
#Los valores propios de la inversa de A son los reciprocos de los valores propios de A
min_valor_propio= 1/(((zk.T@B)@zk)/np.linalg.norm(zk)**2)
min_valor_propio

-0.5857864376269051

In [44]:
#Si v es un vector propio de A^-1 asociado al valor propio lambda, 
#entonces v es un vector propio de A asociado al valor propio 1/lambda 
zk

array([0.85355339, 1.20710678, 0.85355339])

**Verificacion** 

In [45]:
A@zk

array([-0.5       , -0.70710678, -0.5       ])

In [46]:
min_valor_propio*zk

array([-0.5       , -0.70710678, -0.5       ])