In [1]:
import numpy as np

---

## **1. Algoritmo de multiplcacion de matrices**

In [2]:
def matrix_mult(A,B):
    '''
    A es una matriz nxm B es una matrix mxp
    
    Metodo retorna la multiplicacion matricial AB
    
    '''
    n = A.shape[0]
    m_a = A.shape[1]
    
    #Si B es un vector columna:
    if B.ndim==1:
        C = np.zeros(n)
        for i in range(m_a):
            #Combinacion lineal de los vectores columna de A, y los escalares como entradas de B 
            C +=B[i]*A[:,i]
        return C
    
    m_b = B.shape[0]
    p = B.shape[1]
    if m_a!=m_b:
        print("Dimensiones no coinciden")
        return None
    
    C = np.zeros((n,p))
    
    for i in range(n):
        for j in range(p):
            C[i,j] = np.dot(A[i,:],B[:,j])
    return C

## **a)**

In [3]:
A = np.array([
    [5,-4,-2],
    [5,-5,4],
    [2,5,-4],
    [-5,4,3],
    [3,-4,-3]
]
)

B = np.array([5,-2,-3])

matrix_mult(A,B)

array([ 39.,  23.,  12., -42.,  32.])

## **b)**

In [4]:
A = np.array([
    [0,-1,-1,3],
    [5,-5,-2,2],
    [1,0,4,5]
])

B = np.array([
    [0,-3],
    [-2,-1],
    [3,-3]]
)

matrix_mult(A,B)

Dimensiones no coinciden


## **c)**

In [5]:
A = np.array([
    [2,-5,5,1],
    [5,2,-7,-6],
    [-6,-1,7,-4],
    [5,4,1,-5]
])

B = np.array([
    [0,4,-7,1,-6],
    [-1,-6,-5,1,1],
    [2,-1,-6,5,-5],
    [3,-6,6,3,5]
])

In [6]:
matrix_mult(A,B)

array([[ 18.,  27., -13.,  25., -37.],
       [-34.,  51., -39., -46., -23.],
       [  3.,  -1., -19.,  16., -20.],
       [-17.,  25., -91.,  -1., -56.]])

## **Multiplicacion de matrices no es conmutativa**

In [23]:
A = np.array([[1,2],
            [-1,0]])

In [22]:
B = np.array([[0,np.pi],
            [-1,0]])

----

## **2. Reduccion Gaussiana**

In [7]:
def triangular(M):
    '''Retorna una matriz triangular a partir de la matriz como parametro'''
    A = M.copy()
    
    for i in range(0, M.shape[0]):
        pivot = A[i,i]
        #print(pivot)
        A[i,:]= A[i,:]/A[i,i]
        for j in range(i+1,M.shape[0]):
            k = A[j,i] 
            A[j,:]-= k*A[i,:]
            
    return A

In [8]:
def back_substitution(M, b):
    '''
    Args:
        A (np.array): Matriz de coeficientes triangular superior
        b (np.arra): vector de constantes
        
    '''
    A= M.copy()
    
    n = np.shape(A)[0]

    x = np.zeros(n)

    for i in range(n-1,-1,-1):
        sum = b[i]
        for j in range(n-1,i,-1):
            sum -= A[i,j]*x[j]
        x[i] = sum/A[i,i]

    return x

## **a)**

In [9]:
A = np.array([
    [3,1,-1],
    [1,-2,1],
    [4,-1,1]
])

b = np.array([2,0,3])

n = np.shape(A)[0]
M = np.zeros(shape=(n,n+1))

M[:,0:n] = A
M[:,n] = b

In [10]:
C = triangular(M)
C

array([[ 1.        ,  0.33333333, -0.33333333,  0.66666667],
       [-0.        ,  1.        , -0.57142857,  0.28571429],
       [ 0.        ,  0.        ,  1.        ,  1.        ]])

In [11]:
A = C[:,:3].copy()
b = C[:,3:].copy()

In [12]:
#Solucion
mysol = back_substitution(A,b)
mysol

array([0.71428571, 0.85714286, 1.        ])

## **b)**

In [15]:
A = np.array([
    [1,1,1],
    [0,-8,10],
    [4,-8,0]
])

b = np.array([0,0,6])

n = np.shape(A)[0]
M = np.zeros(shape=(n,n+1))

M[:,0:n] = A
M[:,n] = b

In [16]:
C = triangular(M)
C

array([[ 1.        ,  1.        ,  1.        ,  0.        ],
       [-0.        ,  1.        , -1.25      , -0.        ],
       [-0.        , -0.        ,  1.        , -0.31578947]])

In [17]:
A = C[:,:3].copy()
b = C[:,3:].copy()

In [18]:
#Solucion
mysol = back_substitution(A,b)
mysol

array([ 0.71052632, -0.39473684, -0.31578947])

---

## **3. Valores y vectores propios**

In [ ]:
np.array(
    [],
    [],
    

)