In [1]:
import numpy as np

In [91]:
def matrix_mult(A,B):
    '''A es una matriz nxm B es una matrix mxp'''
    n = A.shape[0]
    m_a = A.shape[1]
    m_b = A.shape[0]
    p = A.shape[1]
    
    if B.ndim==1:
        C = np.zeros(n)
        for i in range(m_a):
            C +=B[i]*A[:,i]
        return C
    
    if m_a!=m_b:
        print("Dimensiones no coinciden")
        return None
    
    C = np.zeros((n,p))
    
    for i in range(n):
        for j in range(p):
            C[i,j] = A[i,:]@B[:,j]
    return C

In [92]:
A = np.array([
    [5,-4,-2],
    [5,-5,4],
    [2,5,-4],
    [-5,4,3],
    [3,-4,-3]
]
)

B = np.array([5,-2,-3])

matrix_mult(A,B)

array([ 39.,  23.,  12., -42.,  32.])

In [93]:
A = np.array([
    [0,-1,-1,3],
    [5,-5,-2,2],
    [1,0,4,5]
])

B = np.array([
    [0,-3],
    [-2,-1],
    [3,-3]]
)

matrix_mult(A,B)

Dimensiones no coinciden


In [94]:
A = np.array([
    [2,-5,5,1],
    [5,2,-7,-6],
    [-6,-1,7,-4],
    [5,4,1,-5]
])

B = np.array([
    [0,4,-7,1,-6],
    [-1,-6,-5,1,1],
    [2,-1,-6,5,-5],
    [3,-6,6,3,5]
])

In [95]:
matrix_mult(A,B)

array([[ 18.,  27., -13.,  25.],
       [-34.,  51., -39., -46.],
       [  3.,  -1., -19.,  16.],
       [-17.,  25., -91.,  -1.]])

----

## **Reduccion Gaussiana**

In [126]:
def triangular(M):
    A = M.copy()
    
    for i in range(0, M.shape[0]):
        pivot = A[i,i]
        #print(pivot)
        A[i,:]= A[i,:]/A[i,i]
        for j in range(i+1,M.shape[0]):
            k = A[j,i] 
            A[j,:]-= k*A[i,:]
            
    return A

In [134]:
def back_substitution(A, b):
    '''
    Args:
        A (np.array): Matriz de coeficientes triangular superior
        b (np.arra): vector de constantes
        
    '''

    n = np.shape(A)[0]

    x = np.zeros(n)

    for i in range(n-1,-1,-1):
        sum = b[i]
        for j in range(n-1,i,-1):
            sum -= A[i,j]*x[j]
        x[i] = sum/A[i,i]

    return x

In [136]:
A = np.array([
    [3,1,-1],
    [1,-2,1],
    [4,-1,1]
])

b = np.array([2,0,3])

n = np.shape(A)[0]
M = np.zeros(shape=(n,n+1))

M[:,0:n] = A
M[:,n] = b

In [143]:
C = triangular(M)
C

array([[ 1.        ,  0.33333333, -0.33333333,  0.66666667],
       [-0.        ,  1.        , -0.57142857,  0.28571429],
       [ 0.        ,  0.        ,  1.        ,  1.        ]])

In [144]:
A = C[:,:3].copy()
b = C[:,3:].copy()

In [145]:
back_substitution(A,b)

array([0.71428571, 0.85714286, 1.        ])